[package]
name = "quote-client"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
env_logger = "0.11"
log = "0.4"
quote-core = { path = "../quote-core" }

[dev-dependencies]
tempfile = "3"
